<?php

namespace App\Filament\Pages;

use Filament\Pages\Page;
use Illuminate\Support\Facades\Auth;
use Filament\Notifications\Notification;
use function PHPUnit\Framework\isJson;

class Notifications extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-inbox-arrow-down';

    protected static string $view = 'filament.pages.notifications';

    public static function getNavigationBadge(): ?string
    {

        Auth::user()->notify(
            Notification::make()
                ->title('Saved successfully')
                ->body(json_encode([1 => 2]))
                ->toDatabase(),
        );

        return 1; // TODO: Change the autogenerated stub
    }
}
