<?php

namespace App\Filament\Pages;

use Filament\Actions\Action;
use Filament\Pages\Page;
use Illuminate\Support\Facades\Auth;
use Filament\Notifications\Notification;
use function PHPUnit\Framework\isJson;

class Requests extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-inbox';

    protected static string $view = 'filament.pages.requests';


    public static function getNavigationBadge(): ?string
    {
        /*
        Auth::user()->notify(
            new \App\Notifications\Requests(
                'Ya tienes disponible tu nómina!',
                'Ya puedes entrar y ver tu nómina.',
                'wtf.com',
                'Ver'
            )
        );
        */

        return Auth::user()->unreadNotifications->count(); // TODO: Change the autogenerated stub
    }
}
