<?php

namespace App\Filament\Pages;

use App\Models\Request;
use App\Models\Requestable;
use Filament\Actions\Action;
use Filament\Pages\Page;
use Illuminate\Support\Facades\Auth;
use Filament\Notifications\Notification;
use function PHPUnit\Framework\isJson;

class Requests extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-inbox';

    protected static string $view = 'filament.pages.requests';


    public static function getNavigationBadge(): ?string
    {
        /*
        Auth::user()->notify(
            new \App\Notifications\Requests(
                'Ya tienes disponible tu nómina!',
                'Ya puedes entrar y ver tu nómina.',
x                   'wtf.com',
                'Ver'
            )
        );
        */

        return Requestable::query()->where('user_id', Auth::id())->count(); // TODO: Change the autogenerated stub
    }

    public $requests = [];

    public function mount()
    {
        $this->requests = Requestable::query()
            ->where('user_id', Auth::id())
            ->with([
                'userTo',
                'contract:id,user_id',
                'contract.user:id,name,email',
                'request',
                'requestable'
            ])
            ->orderByDesc('created_at')
            ->get();
    }
}
